### ISSUE TITLE
Should not try to initialize new app database if package install fails

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitz#1322]
### What is the problem?

If package installation fails during new app set up, currently we still try to initialize the DB, but this is guaranteed to fail because node_modules aren't installed.

So we need to be sure to skip db setup if npm install fails.

Here's where db init begins: https://github.com/blitz-js/blitz/blob/canary/packages/cli/src/commands/new.ts#L100

### Versions

```
0.24.2
```

### Other

```
CREATE    .gitignore
CREATE    app/components/Form.tsx
CREATE    app/components/LabeledTextField.tsx

⚠️  Failed to fetch latest version of 'babel-eslint', falling back to '10.x'.
⚠️  Failed to fetch latest version of '@prisma/client', falling back to '2.x'.
⚠️  Failed to fetch latest version of '@testing-library/react', falling back to '11.x'.
⚠️  Failed to fetch latest version of '@typescript-eslint/parser', falling back to '4.x'.
⚠️  Failed to fetch latest version of '@testing-library/react-hooks', falling back to '3.x'.
⚠️  Failed to fetch latest version of 'husky', falling back to '4.x'.
⚠️  Failed to fetch latest version of 'zod', falling back to '1.x'.
⚠️  Failed to fetch latest version of 'eslint-plugin-import', falling back to '2.x'.
⚠️  Failed to fetch latest version of 'react-final-form', falling back to '6.x'.
⚠️  Failed to fetch latest version of 'pretty-quick', falling back to '3.x'.
⚠️  Failed to fetch latest version of 'eslint-plugin-react', falling back to '7.x'.
⚠️  Failed to fetch latest version of 'eslint-plugin-flowtype', falling back to '5.x'.
⚠️  Failed to fetch latest version of '@types/secure-password', falling back to '3.x'.
⚠️  Failed to fetch latest version of 'jest-watch-typeahead', falling back to '0.x'.
⚠️  Failed to fetch latest version of '@prisma/cli', falling back to '2.x'.
⚠️  Failed to fetch latest version of 'eslint-plugin-react-hooks', falling back to '4.x'.
⚠️  Failed to fetch latest version of 'eslint-config-react-app', falling back to '5.x'.
⚠️  Failed to fetch latest version of 'eslint-plugin-jsx-a11y', falling back to '6.x'.
⚠️  Failed to fetch latest version of 'lint-staged', falling back to '10.x'.
⚠️  Failed to fetch latest version of 'react-test-renderer', falling back to '16.x'.
⚠️  Failed to fetch latest version of 'eslint', falling back to '7.x'.
⚠️  Failed to fetch latest version of 'ts-jest', falling back to '26.x'.
⚠️  Failed to fetch latest version of 'prettier', falling back to '2.x'.
⚠️  Failed to fetch latest version of '@types/react', falling back to '16.x'.
⚠️  Failed to fetch latest version of '@testing-library/jest-dom', falling back to '5.x'.
⚠️  Failed to fetch latest version of 'final-form', falling back to '4.x'.
⚠️  Failed to fetch latest version of 'typescript', falling back to '4.x'.
⚠️  Failed to fetch latest version of 'jest', falling back to '26.x'.
⚠️  Failed to fetch latest version of '@typescript-eslint/eslint-plugin', falling back to '4.x'.
⚠️  Failed to fetch latest version of '@types/jest', falling back to '26.x'.
⚠️  Failed to fetch latest version of 'secure-password', falling back to '4.x'.
⚠️  Failed to fetch latest version of 'jest-environment-jsdom-fourteen', falling back to '1.x'.
⚠️  Failed to fetch latest version of 'react-error-boundary', falling back to '2.x'.
⚠️  Failed to fetch latest version of 'blitz', falling back to 'latest'.
◤ Retrieving the freshest of dependencies
✖ We had some trouble connecting to the network, so we'll skip installing your dependencies right now. Make sure to run 'yarn' once you're connected again.
✔ Committing your app
◢ Initializing SQLite databaseError: Cannot find module '@blitzjs/server'
Require stack:
- /private/tmp/fauna/blitz.config.js
- /Users/b/c/blitz/packages/config/dist/config.cjs.development.js
- /Users/b/c/blitz/packages/config/dist/index.js
- /Users/b/c/blitz/packages/core/dist/core.cjs.development.js
- /Users/b/c/blitz/packages/core/dist/index.js
- /Users/b/c/blitz/packages/server/dist/server.cjs.development.js
- /Users/b/c/blitz/packages/server/dist/index.js
- /Users/b/c/blitz/packages/cli/src/commands/db.ts
- /Users/b/c/blitz/node_modules/@oclif/config/lib/plugin.js
- /Users/b/c/blitz/node_modules/@oclif/config/lib/config.js
- /Users/b/c/blitz/node_modules/@oclif/config/lib/index.js
- /Users/b/c/blitz/packages/cli/node_modules/@oclif/command/lib/command.js
- /Users/b/c/blitz/packages/cli/node_modules/@oclif/command/lib/index.js
- /Users/b/c/blitz/packages/cli/lib/src/index.js
- /Users/b/c/blitz/packages/blitz/dist/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Module._load (internal/modules/cjs/loader.js:864:27)
    at Function._load (/Users/b/c/blitz/node_modules/@salesforce/lazy-require/lib/LazyLoader.js:99:24)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (/Users/b/c/blitz/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/private/tmp/fauna/blitz.config.js:1:127)
    at Module._compile (/Users/b/c/blitz/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Module._load (internal/modules/cjs/loader.js:901:14)
```

**Comment by flybayer** [comment]
nevermind, db init is being handled if it fails

**Comment by Ajeethkumar-r** [comment]
Hi, I try to blitz app but it does not initialize SQLlite database, what to do

**Comment by beerose** [comment]
Hi @Ajeethkumar-r, that should be fixed in the latest release. Could you update Blitz and try again?

And in your current project, you can run `blitz prisma migrate dev` to initialize the DB.

**Comment by walidmourou** [comment]
**I still have the same issue with the latest blitz version. When I create a new app, I get this**


> *\> blitz new todo*
√ You have the latest Blitz version
√ Pick a new project's language · JavaScript
√ Pick your new app template · full
√ Install dependencies? · npm
√ Pick a form library (you can switch to something else later if you want) · React Final Form
Hang tight while we set up your new Blitz app!
CREATE ... (all files are created)
√ Retrieving the freshest of dependencies
√ Installing those dependencies (this will take a few minutes)
**× Initializing SQLite database**
√ Formatting your code
√ Committing your app

**Here is my packages version:**

> *\> npm -g list*
├── blitz@0.45.3
├── create-react-app@5.0.0
├── nodemon@2.0.15
├── npm@8.5.1
├── serve@11.3.2
└── yarn@1.22.17

**More infrastructure details:**

> *\> blitz --version*
Windows 10 | win32-x64 | Node: v16.14.0
blitz: 0.45.3 (global)
  Package manager: npm
  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 18.01 GB / 31.72 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: Not Found
    prisma: Not Found
    react: Not Found
    react-dom: Not Found
    typescript: Not Found

**and when I run:**

> \> *blitz prisma migrate dev*
\~\AppData\Roaming\npm\node_modules\blitz\node_modules\next\dist\server\lib\utils.js:65
        throw new Error('Unable to find project root by looking for your package.json or for ' + _constants.CONFIG_FILE);
Error: Unable to find project root by looking for your package.json or for .blitz.config.compiled.js at getProjectRoot (\~\AppData\Roaming\npm\node_modules\blitz\node_modules\next\dist\server\lib\utils.js:65:15)
