### ISSUE TITLE
Api files from sub or container directories are copied in one api file, but path of imports are not adjusted

### ISSUE THREAD

**Issue by kivi** [blitz-js/blitz#1754]
### What is the problem?

Files and directories api, which are in in container directories. (With container directories I mean for example> `pages/auth/`). 
Are accumulate into `.blitz/caches/dev/app/pages/api/`

When placed from container directories into app/pages/api, the imports are not copied.

### Steps to Reproduce

Check the file `app/auth/api/auth/[[...path]].js`
https://codesandbox.io/s/vibrant-boyd-x2fp6?file=/app/auth/api/auth/%5B%5B...path%5D%5D.ts

Here the line:
import { runCORSMiddleware, getCors } from "../../supertokens";

1.

### Versions

blitz: 0.29.2

### Other

```
Module not found: Can't resolve '../../supertokens'
  1 | import { superTokensMiddleware } from "supertokens-node/nextjs";
> 2 | import { runCORSMiddleware, getCors } from "../../supertokens";
  3 |
```

That happens in ./pages/api/auth/[[...path]].ts:2:0  in .blitz
The file I have edited is in app/auth/api/[[...path]].ts and the file not found is in app/auth/ but I the imports are not resolved correctly, when blitz is accumulate all api  files and directories into one root api directory.

**Comment by flybayer** [comment]
Fixed in https://github.com/blitz-js/blitz/releases/tag/v0.29.3

**Comment by kivi** [comment]
This is not fixed.

Versions: 
`blitz: 0.29.2 (global)
blitz: 0.29.2 (local)`

Files in /api directories of "container directories" are created in .blitz/cache/dev/pages/api, but the rest of the container directories will be created in .blitz/cache/dev/app/container.

`import { doSometthing } from "../../fileInContainerDirectoryDoSomething"` in app/container/api/subdir/path.ts is not being updated in the caches to `import { doSometthing } from "../../../app/container/fileInContainerDirectoryDoSomething"`

**Comment by kivi** [comment]
Sorry, I misread and I am still using the old version.

But I can not upgrade. First I tried to upgrade with `yarn`.

Then I tried to create a new blitz project: `blitz new myproject`



```
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

? Your global blitz version is outdated. Upgrade? ... 
> Yes - Upgrade to 0.29.3
  No - Continue with old version (0.29.2) - NOT recommended

# ....
yarn global v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
# ....

[4/4] Building fresh packages...

success Installed "blitz@0.29.3" with binaries:
      - blitz
Done in 6.15s.
 »   Error: Unable to upgrade blitz, please run `blitz new` again and 
 »   select No to skip the upgrade
```

**Comment by flybayer** [comment]
@kivi inside your current blitz project, run `yarn add blitz@0.29.3`, and then run `blitz start`. That's all you need to do
