### ISSUE TITLE
Rendering a component with a Link multiple times in a test results in console errors

### ISSUE THREAD

**Issue by zenhob** [blitz-js/blitz#2117]
### What is the problem?

When a `Link` is rendered by multiple tests in a suite, errors appear on every render after the first one: `Warning: An update to Link inside a test was not wrapped in act(...).`

### Paste all your error logs here:

```
$ npx jest app/components/LinkWrapper.test.tsx
 PASS   CLIENT  app/components/LinkWrapper.test.tsx
  ✓ renders (24 ms)
  ✓ renders again (31 ms)

  console.error
    Warning: An update to Link inside a test was not wrapped in act(...).

    When testing, code that causes React state updates should be wrapped into act(...):

    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */

    This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at Link
        at LinkWrapper
        at wrapper

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:25800:9)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:16798:9)
      at node_modules/next/client/use-intersection.tsx:47:3
      at node_modules/next/client/request-idle-callback.ts:27:9

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        1.584 s, estimated 2 s
Ran all test suites matching /app\/components\/LinkWrapper.test.tsx/i.
```

### Paste all relevant code snippets here:

LinkWrapper.test.tsx:

```
import LinkWrapper from "./LinkWrapper"
import { render } from "test/utils"

it("renders", () => {
  render(<LinkWrapper>Hi</LinkWrapper>)
})
it("renders again", () => {
  render(<LinkWrapper>Hi</LinkWrapper>)
})

```

LinkWrapper.tsx:

```
import { Link } from "blitz"

export default function LinkWrapper({ children }) {
  return (
    <Link prefetch={false} href="/">
      {children}
    </Link>
  )
}
```

### What are detailed steps to reproduce this?

1. write a test that renders two Links
2. observe errors in the console during test runs

### Run `blitz -v` and paste the output here:

```
You are using beta software - if you have any problems, please open an issue here:
      https://github.com/blitz-js/blitz/issues/new/choose

Linux 5.4 | linux-x64 | Node: v14.8.0

blitz: 0.32.1 (local)

  Package manager: npm
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 1014.98 MB / 15.33 GB
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.8.0/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: 2.18.0 => 2.18.0
    blitz: 0.32.1 => 0.32.1
    prisma: 2.18.0 => 2.18.0
    react: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    react-dom: 0.0.0-experimental-3310209d0 => 0.0.0-experimental-3310209d0
    typescript: 4.0.5 => 4.0.5



```

**Comment by flybayer** [comment]
I think this should be fixed like this:


```tsx
import LinkWrapper from "./LinkWrapper"
import { render } from "test/utils"

it("renders", () => {
  act(() => {
    render(<LinkWrapper>Hi</LinkWrapper>)
  })
})
it("renders again", () => {
  act(() => {
    render(<LinkWrapper>Hi</LinkWrapper>)
  })
})
```

**Comment by zenhob** [comment]
Thanks for the suggestion, @flybayer but that did not fix it, I get the same result when I call `render` in an `act` callback.

**Comment by zenhob** [comment]
Again, this doesn't happen when there is only one test, is some kind of state persisting between the tests? Do I need to clear the screen or something?

**Comment by flybayer** [comment]
Ok odd. This was fixed in next.js in 10.0.7, so surprised you have this. We may need to implement some of the same changes as they did in https://github.com/vercel/next.js/pull/22072. Also maybe this will just be fixed with our next.js fork integration.


For now I suggest following this workaround: https://github.com/vercel/next.js/issues/20048#issuecomment-755028887

**Comment by Elias-Graf** [comment]
What version of Next.js are you guys using? Because this is happening to me given the following packages:

```json
"next": "^11.0.1",
"react": "^17.0.2",
"react-dom": "^17.0.2",
```

Thus it's probably not on you to fix this.
