### ISSUE TITLE
intermittent CSRFTokenMismatchError

### ISSUE THREAD

**Issue by remjx** [blitz-js/blitz#2534]
### What is the problem?

My app is throwing CSRFTokenMismatchError during queries.

I haven't been able to narrow down why this is happening:
- One time I found that the `myAppCookiePrefix_sAntiCsrfToken` was set to "undefined". Clearing the cookies and refreshing fixed the problem
- Sometimes after waiting a few minutes and refreshing it fixes itself
- Opening the page in an incognito window does not fix the problem

So far I've seen this happen on Chrome for Android and Firefox on Windows.

### Run `blitz -v` and paste the output here:

My app is on v0.38.0.

### Environment
```
Vercel

  npmPackages:
    @prisma/client: 2.24.1 => 2.24.1
    blitz: 0.38.0 => 0.38.0
    prisma: 2.24.1 => 2.24.1
    react: ^18.0.0-alpha-c96b78e0e => 18.0.0-alpha-e6be2d531
    react-dom: ^18.0.0-alpha-c96b78e0e => 18.0.0-alpha-e6be2d531
    typescript: ^4.3.2 => 4.3.4
```

**Comment by flybayer** [comment]
@remjx could this be the same issue as https://github.com/blitz-js/blitz/issues/2448?

**Comment by remjx** [comment]
@flybayer I did find a situation where my sAntiCsrfToken was undefined, but I am not using $setPublicData at all, and furthermore I have experienced this issue even when sAntiCsrfToken is defined.

**Comment by flybayer** [comment]
@remjx do you notice it happens more on certain pages than others? And if so, what's unique about those pages? Using many queries? Or using the nextjs data hooks? Or API routes?

**Comment by flybayer** [comment]
So the core bug fixed by #2448 affected any call to `getSessionKernel` for anonymous users. So it's still very possible that is the same bug. I'll leave this open until I get that published and you can test it.

**Comment by remjx** [comment]
The only similarity I've been able to identify is that all the problematic pages use the getCurrentUser query.

I'm following that issue now so I'll be sure to test it, although I haven't found a way to replicate. It's just been happening intermittently.

**Comment by flybayer** [comment]
That fix is released: https://github.com/blitz-js/blitz/releases/tag/v0.38.3

**Comment by remjx** [comment]
@flybayer after upgrading to 0.38.4 I am still encountering this issue. Here are the error logs from Vercel. You'll notice it is logging `Internal error: antiCSRFToken is being set to undefined`

```
[POST] /api/auth/queries/getCurrentUser
13:17:32:98
2021-07-08 17:17:33.050 ERROR Error while processing the request 
 CSRFTokenMismatchError  
details:
{
  name: 'CSRFTokenMismatchError',
  statusCode: 401
```

and

```
[HEAD] /api/auth/queries/getCurrentUser
13:17:32:85
2021-07-08 17:17:32.940 ERROR Error while processing the request 
 Error  Internal error: antiCSRFToken is being set to undefined
error stack:
• blitzjs-core-server.cjs.prod.js:506 assert$1
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:506:25
• blitzjs-core-server.cjs.prod.js:994 setCSRFCookie
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:994:3
• blitzjs-core-server.cjs.prod.js:1299 refreshSession
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1299:5
• blitzjs-core-server.cjs.prod.js:1102 getSessionKernel
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:1102:15
• blitzjs-core-server.cjs.prod.js:702 getSession
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:702:23
• blitzjs-core-server.cjs.prod.js:661 blitzSessionMiddleware
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:661:7
• blitzjs-core-server.cjs.prod.js:83 handleRequestWithMiddleware
    node_modules/@blitzjs/core/server/dist/blitzjs-core-server.cjs.prod.js:83:5
• api-utils.js:8 apiResolver
    node_modules/next/dist/next-server/server/api-utils.js:8:1
• 3760.js:12 <anonymous>
    .next/serverless/chunks/3760.js:12:391
```

**Comment by flybayer** [comment]
Ok! I'm quite confident the remaining issue is fixed in https://github.com/blitz-js/blitz/releases/tag/v0.38.5.

Of course if it's not, please reopen. I really appreciate you working with me on this!

**Comment by remjx** [comment]
@flybayer the CSRF error seems to be fixed! The only caveat is that i had to clear my cookies on mobile Chrome to get past the error. 

Thank you!
