### ISSUE TITLE
next-ui recipe stuck "generating file diff" 

### ISSUE THREAD

**Issue by JackDevAU** [blitz-js/blitz#4189]
### What is the problem?

I've just created a new project, without auth. I wanted to try and use `next-ui` using the blitz cli but when I use the `blitz install next-ui` command it fails to "generate file diffs"
When updating "the `LabeledTextField` wit Next UI's `Input` Component"

### Paste all your error logs here:

```
  ERROR  The "path" argument must be of type string or an instance of Buffer or URL. Received undefined

 node:fs:592:10

 - Object.openSync (node:fs:592:10)
 - Object.readFileSync (node:fs:468:35)
 -  (recipe-install/node_modules/blitz/dist/installer.cjs:478:44)
 -     at Generator.next (<anonymous>)
 - fulfilled (recipe-install/node_modules/blitz/dist/installer.cjs:439:24)
 - processTicksAndRejections (node:internal/process/task_queues:95:5)

2023-08-02 14:39:49.850 ERROR   []
 TypeError  The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
error stack:
  • fs  Object.openSync
        fs:592
  • fs  Object.readFileSync
        fs:468
  • \recipe-install\node_modules\blitz\dist\installer.cjs
        \recipe-install\node_modules\blitz\dist\installer.cjs:478
  •

  • \recipe-install\node_modules\blitz\dist\installer.cjs       fulfilled
        \recipe-install\node_modules\blitz\dist\installer.cjs:439
  • task_queues processTicksAndRejections
        internal\process\task_queues:95
```

### Paste all relevant code snippets here:

N/A

### What are detailed steps to reproduce this?

1. Using the cli `blitz new testing-blitz-next-ui`
	1.  √ Pick a new project's language » TypeScript
	2. √ Pick your new app template » Minimal — no DB, no auth
	3. √ Install dependencies? » npm
4.  cd into folder
5. install next-ui `blitz install next-ui`
6. See error when "Updating LabeledTextField" 

### Run `blitz -v` and paste the output here:

```
Blitz version: 2.0.0-beta.31 (global)
Blitz version: 2.0.0-beta.31 (local)
Windows 11 | win32-x64 | Node: v18.14.1


 Package manager: npm

  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 6.13 GB / 31.74 GB
  Binaries:
    Node: 18.14.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 9.3.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  npmPackages:
    @blitzjs/auth: 2.0.0-beta.31 => 2.0.0-beta.31
    @blitzjs/next: 2.0.0-beta.31 => 2.0.0-beta.31
    @blitzjs/rpc: 2.0.0-beta.31 => 2.0.0-beta.31
    @prisma/client: Not Found
    blitz: 2.0.0-beta.31 => 2.0.0-beta.31
    next: 13.4.5 => 13.4.5
    prisma: Not Found
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    typescript: ^4.8.4 => 4.9.5
```

### Please include below any other applicable logs and screenshots that show your problem:

![image](https://github.com/blitz-js/blitz/assets/57518417/d1fc266e-16e9-44db-82b8-5726084f1737)
Figure: Stuck generating file diff

**Comment by bdlowery** [comment]
I am experience the same problem, but with the tailwind recipe - #4192

**Comment by openspaceranger** [comment]
I experienced the same problem with both tailwind and material ui. Is it possible to force it now to diff aside from killing the process?

**Comment by Doc0x1** [comment]
I'm going to work on getting this issue fixed. Pretty sure I know what the cause is.

**Comment by siddhsuresh** [comment]
that's great @Doc0x1! I will assign this issue to you. Feel free to tag me and we can get the fix merged.

**Comment by Doc0x1** [comment]
> that's great @Doc0x1! I will assign this issue to you. Feel free to tag me and we can get the fix merged.

Okay cool, I'm actually done writing up a issue discussing the problem with the code at length, since it's a multi-layered problem and I thought it'd be worth trying to get some context/ideas/suggestions from others who might have some good strategies or ideas to lend me. It's here if you wanna check it out: #4286

**Comment by Rogant** [comment]
This issue is still active I tried material-ui, next-ui, bumbag-ui and Chakra UI
