### ISSUE TITLE
Dev build broken with Turbopack and Next.js 15 latest

### ISSUE THREAD

**Issue by fungilation** [blitz-js/blitz#4395]
### What is the problem?

with Next 15.0.3, blitz dev --turbo:

![image](https://github.com/user-attachments/assets/77846df1-1236-42f0-9d8c-ab3d463b6c2e)

the error log is misleading (maybe) with the imports in `node_modules/blitz/dist/chunks/index-browser.mjs`, as the culprit is `The export default was not found in module [project]/node_modules/.blitz/turbopack-empty.js [client] (ecmascript).`

bisecting which Next version broke this, it started with 15.0.0-rc.1. 15.0.0-rc.0 and 14.x worked fine in dev --turbo

### Paste all your error logs here:

with Next 15.0.3, dev --turbo:

<img width="1394" alt="image" src="https://github.com/user-attachments/assets/56630496-cf1b-4676-9d8e-c975800feb46">

with Next 15.0.0-rc.0, dev --turbo:

<img width="757" alt="image" src="https://github.com/user-attachments/assets/91e227a3-bd07-40ac-be8e-9096e4abe11b">

### Paste all relevant code snippets here:

N/A

### What are detailed steps to reproduce this?

1. `blitz dev --turbo` with different Next versions
2. also tested different Blitz versions, isn't a factor. Both 2.0.10 and 2.1.3 lead to same error

### Run `blitz -v` and paste the output here:

```
macOS Unknown | darwin-x64 | Node: v23.3.0

blitz: 0.45.5 (global)
blitz: 2.1.3 (local)

  Package manager: npm
  System:
    OS: macOS 14.7.1
    CPU: (8) x64 Apple M1
    Memory: 83.97 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 23.3.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.9.0 - /usr/local/bin/npm
    Watchman: Not Found
  npmPackages:
    @prisma/client: Not Found
    blitz: 2.1.3 => 2.1.3
    prisma: Not Found
    react: 19.0.0-rc-66855b96-20241106 => 19.0.0-rc-66855b96-20241106
    react-dom: 19.0.0-rc-66855b96-20241106 => 19.0.0-rc-66855b96-20241106
    typescript: ~5.4.5 => 5.4.5
```

**Comment by Daidalos117** [comment]
Is this already fixed? I am still getting the error with blitz 2.2.0.

**Comment by fungilation** [comment]
It is fixed


---
Regards,
Gary

**Comment by Daidalos117** [comment]
Yes thank you, I needed to remove node_modules and reinstall. It's working fine now :)

**Comment by consuelo-sanna** [comment]
Hi guys, I'm still seeing an error after updating Next and blitz to latest versions - looks like it works but I'm just unsure on how to fix the following:

Loaded env from /Users/consuelo/Documents/Projects/provider-web/.env.stag
Loaded env from /Users/consuelo/Documents/Projects/provider-web/.env.local
{
  "errno": -2,
  "code": "ENOENT",
  "syscall": "open",
  "path": "/Users/consuelo/Documents/Projects/next-project/node_modules/next/dist/client/on-recoverable-error.js"
}
✔ Routes manifest was successfully generated
   ▲ Next.js 15.1.6
   - Local:        http://localhost:3000
   - Network:      http://192.168.1.14:3000
   - Environments: .env.local

Can you give me a hand?
are ye also experiencing this?

I *think* it comes from codegenTasks.mjs and was introduced here https://github.com/blitz-js/blitz/issues/4232 to patch Next 13, I was wondering if it was safe to remove it or if I'm on the wrong track

**Comment by Daidalos117** [comment]
Getting same error.
